apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
  labels:
    app: tictactoe
spec:
  selector:
    matchLabels:
      app: tictactoe
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
        - name: tictactoe
          image: klmcwhirter/tictactoe
          ports:
            - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - tictactoe
                topologyKey: kubernetes.io/tictactoe
